import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ReduxProvider } from '@/utils/redux/provider'
import { MUIThemeRegistry } from '@/styles/provider'
import { SWRConfigProvider } from '@/utils/providers/SWRConfigProvider'
import type { Session } from 'next-auth'
import NextAuthProvider from '@/utils/providers/NextAuthProvider'
import { BottomBar } from '@/components/global/BottomBar'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode
  session: Session
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
          rel='stylesheet'
        ></link>
        <link
          href='https://fonts.googleapis.com/icon?family=Material+Icons+Outlined'
          rel='stylesheet'
        ></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider session={session}>
          <MUIThemeRegistry options={{ key: 'mui' }}>
            <ReduxProvider>
              <SWRConfigProvider>
                <div>
                  {children}
                  <BottomBar />
                </div>
              </SWRConfigProvider>
            </ReduxProvider>
          </MUIThemeRegistry>
        </NextAuthProvider>
      </body>
    </html>
  )
}
